apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:75d295a848bf07b2845ea4636c80571b933f2a40f7f12df1922d4ccbf03ab4ac
    meta.helm.sh/release-name: kubernetes-cluster
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-06-08T01:10:50.695194073Z"
    reconcile.fluxcd.io/requestedAt: "2025-06-08T01:10:50.695194073Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-cluster
    helm.toolkit.fluxcd.io/name: kubernetes-cluster
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-cluster-cozy-victoria-metrics-operator
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-victoria-metrics-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-cluster
    namespace: tenant-test
  - name: kubernetes-cluster-cilium
    namespace: tenant-test
  - name: kubernetes-cluster-cert-manager-crds
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-cluster-admin-kubeconfig
  releaseName: cozy-victoria-metrics-operator
  storageNamespace: cozy-victoria-metrics-operator
  targetNamespace: cozy-victoria-metrics-operator
  upgrade:
    remediation:
      retries: -1
