apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:ce85b36096324558cf86352ff4c289203f1199d3a1a892e781da536887540b5e
    reconcile.fluxcd.io/forceAt: "2025-07-12T14:59:01.921517035Z"
    reconcile.fluxcd.io/requestedAt: "2025-07-12T14:59:01.921517035Z"
  labels:
    cozystack.io/ui: "true"
  name: tenant-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 1.11.0
  interval: 0s
  values:
    etcd: false
    host: test.moomboo.space
    ingress: true
    isolated: false
    monitoring: false
    seaweedfs: false
