apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:e1a063ee6c05a8158326527e972b5fa600f66871f111c509cd5bfa0652f69870
    reconcile.fluxcd.io/forceAt: "2025-08-06T18:05:44.293562444Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-06T18:05:44.293562444Z"
  labels:
    cozystack.io/ui: "true"
  name: tenant-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 1.11.2
  interval: 0s
  values:
    etcd: false
    host: test.moomboo.space
    ingress: true
    isolated: false
    monitoring: false
    seaweedfs: false
