apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-test
  labels:
    app.kubernetes.io/managed-by: Helm
    coztstack.io/target-cluster-name: kubernetes-harvey
    cozystack.io/repository: system
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-harvey-cilium
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      name: kubernetes-harvey-kubeconfig
  releaseName: cilium
  storageNamespace: cozy-cilium
  targetNamespace: cozy-cilium
  upgrade:
    remediation:
      retries: -1
  values:
    cilium:
      enableIPv4Masquerade: true
      ipv4NativeRoutingCIDR: ""
      k8sServiceHost: kubernetes-harvey.tenant-test.svc
      k8sServicePort: 6443
      routingMode: tunnel
