apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:d8cbfb5758df25a7b9a7c515fe5c79d11d98efd7971966f327d4d27275de11bb
    reconcile.fluxcd.io/forceAt: "2025-12-06T14:09:49.442064979Z"
    reconcile.fluxcd.io/requestedAt: "2025-12-06T14:09:49.442064979Z"
  labels:
    cozystack.io/ui: "true"
  name: tenant-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '>= 0.0.0-0'
  interval: 0s
  values:
    etcd: false
    host: test.moomboo.space
    ingress: true
    isolated: false
    monitoring: false
    seaweedfs: false
