apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:2230fd42bae651a9ca6ad65290aeb3c35cb40c8d1bb05e2c5a8151fb9b9ae9cc
    meta.helm.sh/release-name: kubernetes-cluster
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-08-22T20:21:38.41755711Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-22T20:21:38.41755711Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-cluster
    helm.toolkit.fluxcd.io/name: kubernetes-cluster
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-cluster-fluxcd
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-fluxcd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-cluster
    namespace: tenant-test
  - name: kubernetes-cluster-cilium
    namespace: tenant-test
  - name: kubernetes-cluster-fluxcd-operator
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      name: kubernetes-cluster-kubeconfig
  releaseName: fluxcd
  storageNamespace: cozy-fluxcd
  targetNamespace: cozy-fluxcd
  upgrade:
    remediation:
      retries: -1
  values:
    flux-instance:
      instance:
        sync:
          interval: 1m
          kind: GitRepository
          path: ./water-prod
          ref: refs/heads/main
          url: https://github.com/kingdonb/water-monitor.git
