apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:a22b2a6d39d409290389d37ac5a3b65b6ceac16b504d3340679e390d14545fc2
    reconcile.fluxcd.io/forceAt: "2025-11-28T20:44:52.74947321Z"
    reconcile.fluxcd.io/requestedAt: "2025-11-28T20:44:52.74947321Z"
  labels:
    cozystack.io/ui: "true"
  name: tenant-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '*'
  interval: 0s
  values:
    etcd: false
    host: test.moomboo.space
    ingress: true
    isolated: false
    monitoring: false
    seaweedfs: false
