apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-cluster
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.13.0
  interval: 1m0s
  timeout: 5m0s
  values:
    addons:
      certManager:
        enabled: true
      fluxcd:
        enabled: true
        valuesOverride:
          flux-instance:
            instance:
              distribution:
                version: 2.x
      ingressNginx:
        enabled: true
        hosts:
        - water.teamhephy.info
    controlPlane:
      replicas: 2
    host: ""
    nodeGroups:
      md0:
        ephemeralStorage: 20Gi
        instanceType: u1.medium
        maxReplicas: 10
        minReplicas: 0
        resources:
          cpu: ""
          memory: ""
        roles:
        - ingress-nginx
    storageClass: replicated
