apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:34a5a8fca7ea4cb9e44fe14e1e271ec868414fa8ac4f9677c0605d91ce1efa80
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-11-28T20:45:17.006334856Z"
    reconcile.fluxcd.io/requestedAt: "2025-11-28T20:45:17.006334856Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-harvey
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-harvey-coredns
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-coredns
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-test
  - name: kubernetes-harvey-cilium
    namespace: tenant-test
  install:
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-harvey-admin-kubeconfig
  releaseName: coredns
  storageNamespace: kube-system
  targetNamespace: kube-system
  timeout: 10m
  upgrade:
    force: true
    remediation:
      retries: -1
  values:
    coredns:
      service:
        clusterIP: 10.95.0.10
