apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:df7a5d291aa688a324385bd57b0f242de2998c4adbf28a6ab5f2763b7b4550c6
    meta.helm.sh/release-name: kubernetes-cluster
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-07-23T23:02:28.307636405Z"
    reconcile.fluxcd.io/requestedAt: "2025-07-23T23:02:28.307636405Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-cluster
    helm.toolkit.fluxcd.io/name: kubernetes-cluster
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-cluster-fluxcd-operator
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-fluxcd-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-cluster
    namespace: tenant-test
  - name: kubernetes-cluster-cilium
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-cluster-admin-kubeconfig
  releaseName: fluxcd-operator
  storageNamespace: cozy-fluxcd
  targetNamespace: cozy-fluxcd
  upgrade:
    remediation:
      retries: -1
  values:
    flux-operator:
      fullnameOverride: flux-operator
      hostNetwork: false
