apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:75d295a848bf07b2845ea4636c80571b933f2a40f7f12df1922d4ccbf03ab4ac
    reconcile.fluxcd.io/forceAt: "2025-06-08T01:10:50.510820049Z"
    reconcile.fluxcd.io/requestedAt: "2025-06-08T01:10:50.510820049Z"
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-cluster
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.21.0
  interval: 0s
  values:
    addons:
      certManager:
        enabled: true
      fluxcd:
        enabled: true
        valuesOverride:
          flux-instance:
            instance:
              sync:
                interval: 1m
                kind: GitRepository
                path: ./water-prod
                ref: refs/heads/main
                url: https://github.com/kingdonb/water-monitor.git
      ingressNginx:
        enabled: true
        hosts:
        - water.teamhephy.info
      monitoringAgents:
        enabled: true
    controlPlane:
      replicas: 2
    host: ""
    kamajiControlPlane:
      addons:
        konnectivity:
          server:
            resourcesPreset: micro
      apiServer:
        resourcesPreset: small
      controllerManager:
        resourcesPreset: micro
      scheduler:
        resourcesPreset: micro
    nodeGroups:
      md0:
        ephemeralStorage: 20Gi
        instanceType: u1.large
        maxReplicas: 10
        minReplicas: 0
        resources:
          cpu: ""
          memory: ""
        roles:
        - ingress-nginx
    storageClass: replicated
