apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-test
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.10.0
  interval: 1m0s
  timeout: 5m0s
  values:
    addons:
      certManager:
        enabled: true
      fluxcd:
        enabled: true
      ingressNginx:
        enabled: true
    controlPlane:
      replicas: 2
    host: ""
    nodeGroups:
      md0:
        ephemeralStorage: 20Gi
        maxReplicas: 10
        minReplicas: 0
        resources:
          cpu: 2
          memory: 1024Mi
        roles:
        - ingress-nginx
    storageClass: replicated
