apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:75d295a848bf07b2845ea4636c80571b933f2a40f7f12df1922d4ccbf03ab4ac
    meta.helm.sh/release-name: kubernetes-cluster
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-06-08T01:10:50.619524882Z"
    reconcile.fluxcd.io/requestedAt: "2025-06-08T01:10:50.619524882Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-cluster
    helm.toolkit.fluxcd.io/name: kubernetes-cluster
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-cluster-vertical-pod-autoscaler
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-vertical-pod-autoscaler
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-cluster
    namespace: tenant-test
  - name: kubernetes-cluster-monitoring-agents
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-cluster-admin-kubeconfig
  releaseName: vertical-pod-autoscaler
  storageNamespace: cozy-vertical-pod-autoscaler
  targetNamespace: cozy-vertical-pod-autoscaler
  upgrade:
    remediation:
      retries: -1
  values:
    vertical-pod-autoscaler:
      recommender:
        extraArgs:
          container-name-label: container
          container-namespace-label: namespace
          container-pod-name-label: pod
          memory-saver: true
          metric-for-pod-labels: kube_pod_labels{job="kube-state-metrics", tenant="tenant-test",
            cluster="kubernetes-cluster"}[8d]
          pod-label-prefix: label_
          pod-name-label: pod
          pod-namespace-label: namespace
          prometheus-address: http://vmselect-shortterm.tenant-root.svc.cozy.local:8481/select/0/prometheus/
          prometheus-cadvisor-job-name: cadvisor
          storage: prometheus
        resources:
          limits:
            memory: 1600Mi
          requests:
            cpu: 100m
            memory: 1600Mi
