apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:69b8a6eba2f3437c3625d757e03cf7601af492c301fd0365b7109d43c89797a7
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-08-06T18:05:40.680283728Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-06T18:05:40.680283728Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-harvey
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-harvey-cilium
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-harvey-admin-kubeconfig
  releaseName: cilium
  storageNamespace: cozy-cilium
  targetNamespace: cozy-cilium
  upgrade:
    remediation:
      retries: -1
  values:
    cilium:
      enableIPv4Masquerade: true
      ipv4NativeRoutingCIDR: ""
      k8sServiceHost: kubernetes-harvey.tenant-test.svc
      k8sServicePort: 6443
      routingMode: tunnel
