apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:df7a5d291aa688a324385bd57b0f242de2998c4adbf28a6ab5f2763b7b4550c6
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-07-23T23:02:28.37557369Z"
    reconcile.fluxcd.io/requestedAt: "2025-07-23T23:02:28.37557369Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-harvey
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-harvey-csi
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-kubevirt-csi-node
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-harvey-vsnap-crd
    namespace: tenant-test
  - name: kubernetes-harvey
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-harvey-admin-kubeconfig
  releaseName: csi
  storageNamespace: cozy-csi
  targetNamespace: cozy-csi
  upgrade:
    remediation:
      retries: -1
  values:
    storageClass: replicated
