apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:66a9e073401114d3d474afd2dc7b39d4b8dd2f8905743f2e94a4edf73fb69e47
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-07-12T14:59:07.055714868Z"
    reconcile.fluxcd.io/requestedAt: "2025-07-12T14:59:07.055714868Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-harvey
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-harvey-cert-manager
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-cert-manager
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-test
  - name: kubernetes-harvey-cilium
    namespace: tenant-test
  - name: kubernetes-harvey-cert-manager-crds
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-harvey-admin-kubeconfig
  releaseName: cert-manager
  storageNamespace: cozy-cert-manager
  targetNamespace: cozy-cert-manager
  upgrade:
    remediation:
      retries: -1
  values:
    cert-manager:
      webhook:
        networkPolicy:
          enabled: false
