apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:84bea0b8770c34d7f9fa552ff237263f95bca0532e798f21fe3d5303b1351daf
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-test
    reconcile.fluxcd.io/forceAt: "2025-06-18T01:56:05.422408174Z"
    reconcile.fluxcd.io/requestedAt: "2025-06-18T01:56:05.422408174Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: kubernetes-harvey
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: kubernetes-harvey-cert-manager-crds
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-cert-manager-crds
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-test
  - name: kubernetes-harvey-cilium
    namespace: tenant-test
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      key: super-admin.svc
      name: kubernetes-harvey-admin-kubeconfig
  releaseName: cert-manager-crds
  storageNamespace: cozy-cert-manager-crds
  targetNamespace: cozy-cert-manager-crds
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: Secret
    name: kubernetes-harvey-cert-manager-crds-values-override
    valuesKey: values
