apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:dcd2bae8b341c2be896d007f83ec82ae51b682251fb1efa37af0966c485a715c
    reconcile.fluxcd.io/forceAt: "2025-12-06T12:28:21.657313-05:00"
    reconcile.fluxcd.io/requestedAt: "2025-12-06T12:28:21.657313-05:00"
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-harvey
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '>= 0.0.0-0'
  install:
    remediation:
      retries: -1
  interval: 5m0s
  upgrade:
    remediation:
      retries: -1
  values:
    addons:
      certManager:
        enabled: true
        valuesOverride:
          cert-manager:
            webhook:
              networkPolicy:
                enabled: false
      fluxcd:
        enabled: true
        valuesOverride:
          flux-instance:
            instance:
              cluster:
                networkPolicy: false
              sync:
                interval: 1m
                kind: GitRepository
                path: ./clusters/harvey
                ref: refs/heads/main
                url: https://github.com/kingdon-ci/cozy-fleet.git
      gatewayAPI:
        enabled: false
      gpuOperator:
        enabled: false
      ingressNginx:
        enabled: true
        exposeMethod: Proxied
        hosts:
        - '*.harvey.moomboo.space'
        - harvey.moomboo.space
        - dex.harvey.moomboo.space
        - webhook.harvey.moomboo.space
        - water.harvey.moomboo.space
        - moo-cluster.turkey.local
        - mop-cluster.turkey.local
        - vcluster-cluster.turkey.local
        - podinfo.local
        - socryx-topled.arvo.network
      monitoringAgents:
        enabled: false
      velero:
        enabled: false
    controlPlane:
      apiServer:
        resourcesPreset: 2xlarge
      controllerManager:
        resourcesPreset: micro
      konnectivity:
        server:
          resourcesPreset: micro
      replicas: 2
      scheduler:
        resourcesPreset: micro
    host: harvey.test.moomboo.space
    kamajiControlPlane:
      addons:
        konnectivity:
          server:
            resourcesPreset: micro
      apiServer:
        resourcesPreset: medium
      controllerManager:
        resourcesPreset: large
      scheduler:
        resourcesPreset: large
    nodeGroups:
      md0:
        ephemeralStorage: 20Gi
        instanceType: u1.large
        maxReplicas: 10
        minReplicas: 0
        roles:
        - ingress-nginx
    storageClass: replicated
    version: v1.33
