apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    reconcile.fluxcd.io/forceAt: "2025-03-01T20:43:24.452139-05:00"
    reconcile.fluxcd.io/requestedAt: "2025-03-01T20:43:24.452139-05:00"
  labels:
    kustomize.toolkit.fluxcd.io/name: dex
    kustomize.toolkit.fluxcd.io/namespace: cozy-fluxcd
  name: dex
  namespace: dex
spec:
  chart:
    spec:
      chart: dex
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: dex
      version: 0.19.1
  interval: 5m
  storageNamespace: dex
  targetNamespace: dex
  timeout: 1m
  values:
    config:
      connectors:
      - config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          orgs:
          - name: kingdon-ci
            teams:
            - cozy-vcluster-sre
            - weave-gitops
            - home-workers
            - home-guests
          redirectURI: https://dex.harvey.moomboo.space/callback
        id: github
        name: GitHub
        type: github
      expiry:
        idTokens: 90m
        refreshTokens:
          absoluteLifetime: 72h
          validIfNotUsedFor: 10h
      issuer: https://dex.harvey.moomboo.space
      staticClients:
      - id: weave-gitops
        name: Weave GitOps Core
        redirectURIs:
        - https://gitops-staging.howard.moomboo.space/oauth2/callback
        - http://localhost:9001/oauth2/callback
        secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
      - id: weave-gitops-ee
        name: Weave GitOps Enterprise
        redirectURIs:
        - https://mccp.howard.moomboo.space/oauth2/callback
        secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
      - id: weave-gitops-ee-staging
        name: Weave GitOps Enterprise (Staging)
        redirectURIs:
        - https://mccp-staging.howard.moomboo.space/oauth2/callback
        secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
      - id: wg-kubelogin
        name: Weave GitOps Kubelogin
        redirectURIs:
        - http://localhost:8000
        - http://localhost:18000
        secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
      - id: wg-loft
        name: Loft.sh
        redirectURIs:
        - http://loft.loft.svc.cluster.local/auth/oidc/callback
        secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
      storage:
        config:
          inCluster: true
        type: kubernetes
    envVars:
    - name: GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: client-id
          name: github-client
    - name: GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: client-secret
          name: github-client
    image:
      tag: v2.41.1
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      className: tenant-test
      enabled: true
      hosts:
      - host: dex.harvey.moomboo.space
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - dex.harvey.moomboo.space
        secretName: dex-dev-example-tld
