apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: seaweedfs
    meta.helm.sh/release-namespace: tenant-test
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: seaweedfs
    helm.toolkit.fluxcd.io/namespace: tenant-test
  name: seaweedfs-system
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: cozy-seaweedfs
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  values:
    global:
      serviceAccountName: tenant-test-seaweedfs
    seaweedfs:
      cosi:
        bucketClassName: tenant-test
        driverName: tenant-test.seaweedfs.objectstorage.k8s.io
      s3:
        ingress:
          annotations:
            acme.cert-manager.io/http01-ingress-class: tenant-root
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          className: tenant-root
          host: s3.test.moomboo.space
          tls:
          - hosts:
            - s3.test.moomboo.space
            secretName: seaweedfs-s3-ingress-tls
      volume:
        dataDirs:
        - maxVolumes: 0
          name: data1
          size: 10Gi
          type: persistentVolumeClaim
        podAnnotations:
          volume-size: 10Gi
        replicas: 2
