apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-harvey
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.14.0
  interval: 1m0s
  timeout: 5m0s
  values:
    addons:
      certManager:
        enabled: true
        valuesOverride:
          cert-manager:
            webhook:
              networkPolicy:
                enabled: false
      fluxcd:
        enabled: true
        valuesOverride:
          flux-instance:
            instance:
              cluster:
                networkPolicy: false
              sync:
                interval: 1m
                kind: GitRepository
                path: ./clusters/harvey-moomboo-space
                ref: refs/heads/main
                url: https://github.com/kingdon-ci/fleet-infra.git
      ingressNginx:
        enabled: true
        hosts:
        - '*.harvey.moomboo.space'
        - harvey.moomboo.space
        - webhook.harvey.moomboo.space
        - water.harvey.moomboo.space
        - moo-cluster.turkey.local
      monitoringAgents:
        enabled: true
    controlPlane:
      replicas: 2
    host: harvey.test.moomboo.space
    nodeGroups:
      md0:
        ephemeralStorage: 20Gi
        instanceType: u1.large
        maxReplicas: 10
        minReplicas: 0
        resources:
          cpu: ""
          memory: ""
        roles:
        - ingress-nginx
    storageClass: replicated
