apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: tenant-test
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/instance: tenant-test
    app.kubernetes.io/managed-by: Helm
    cozystack.io/ui: "true"
    helm.toolkit.fluxcd.io/name: tenant-test
    helm.toolkit.fluxcd.io/namespace: tenant-root
  name: seaweedfs
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: seaweedfs
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
      version: '*'
  interval: 1m0s
  timeout: 5m0s
