apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:c7d74d62a0fdd65bc6c3a100278fe38d2b8eb5b893fee9ca91076c6942419712
    reconcile.fluxcd.io/forceAt: "2025-09-28T17:03:45.029996983Z"
    reconcile.fluxcd.io/requestedAt: "2025-09-28T13:35:01.790313-04:00"
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-harvey
  namespace: tenant-test
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.29.1
  interval: 0s
  values:
    addons:
      certManager:
        enabled: true
        valuesOverride:
          cert-manager:
            webhook:
              networkPolicy:
                enabled: false
      fluxcd:
        enabled: true
        valuesOverride:
          flux-instance:
            instance:
              cluster:
                networkPolicy: false
              sync:
                interval: 1m
                kind: GitRepository
                path: ./clusters/harvey
                ref: refs/heads/main
                url: https://github.com/kingdon-ci/cozy-fleet.git
      gatewayAPI:
        enabled: false
      gpuOperator:
        enabled: false
      ingressNginx:
        enabled: true
        exposeMethod: Proxied
        hosts:
        - '*.harvey.moomboo.space'
        - harvey.moomboo.space
        - dex.harvey.moomboo.space
        - webhook.harvey.moomboo.space
        - water.harvey.moomboo.space
        - moo-cluster.turkey.local
        - mop-cluster.turkey.local
        - vcluster-cluster.turkey.local
        - podinfo.local
        - socryx-topled.arvo.network
      monitoringAgents:
        enabled: true
      velero:
        enabled: false
    controlPlane:
      apiServer:
        resourcesPreset: 2xlarge
      controllerManager:
        resourcesPreset: micro
      konnectivity:
        server:
          resourcesPreset: micro
      replicas: 2
      scheduler:
        resourcesPreset: micro
    host: harvey.test.moomboo.space
    kamajiControlPlane:
      addons:
        konnectivity:
          server:
            resourcesPreset: micro
      apiServer:
        resourcesPreset: medium
      controllerManager:
        resourcesPreset: large
      scheduler:
        resourcesPreset: large
    nodeGroups:
      md0:
        ephemeralStorage: 20Gi
        instanceType: u1.large
        maxReplicas: 10
        minReplicas: 0
        roles:
        - ingress-nginx
    storageClass: replicated
    version: v1.33
