apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:354074821231337b4e13c16a18e323baec184b935c2d1b784ec2574bf4b11056
    reconcile.fluxcd.io/forceAt: "2025-06-18T01:55:59.791314686Z"
    reconcile.fluxcd.io/requestedAt: "2025-06-18T01:55:59.791314686Z"
  labels:
    cozystack.io/ui: "true"
  name: tenant-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 1.10.0
  interval: 0s
  values:
    etcd: false
    host: test.moomboo.space
    ingress: true
    isolated: false
    monitoring: false
    seaweedfs: false
