machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - http://metnoom-13net.turkey.local:5050

      quay.io:
        endpoints:
          - http://metnoom-13net.turkey.local:5052

      gcr.io:
        endpoints:
          - http://metnoom-13net.turkey.local:5053

      ghcr.io:
        endpoints:
          - http://metnoom-13net.turkey.local:5054

      registry.k8s.io:
        endpoints:
          - http://metnoom-13net.turkey.local:5051
