apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: vm-disk-bastion-root
  namespace: tenant-legacy
spec:
  chart:
    spec:
      chart: vm-disk
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.1.0
  interval: 1m0s
  timeout: 5m0s
  values:
    optical: false
    storage: 225Gi
    storageClass: replicated
