apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: virtual-machine-worker2
  namespace: tenant-legacy
spec:
  chart:
    spec:
      chart: virtual-machine
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.5.0
  interval: 1m0s
  timeout: 5m0s
  values:
    cloudInit: |
      #cloud-config
    external: true
    externalPorts:
    - 22
    instanceProfile: ubuntu
    instanceType: u1.large
    resources:
      disk: 50Gi
    running: true
    sshKeys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOOAEa0lEIJwx2xRQtPbEqw4h55yNBEjlxMfW5cqrq5A
      yebyen@kingdon-mbp.turkey.local
    systemDisk:
      image: ubuntu
      storage: 5Gi
      storageClass: replicated
