---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spin-operator
spec:
  chartRef:
    kind: OCIRepository
    name: spinkube
  interval: 10m0s
  driftDetection:
    mode: enabled
  values:
    controllerManager:
      manager:
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
