apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-headlamp-app
    kustomize.toolkit.fluxcd.io/namespace: default
  name: headlamp
  namespace: default
spec:
  chart:
    spec:
      chart: headlamp
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: headlamp
      version: 0.25.x
  interval: 10m0s
  values:
    config:
      pluginsDir: /build/plugins
    initContainers:
    - command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
      image: ghcr.io/ashu8912/flux-plugin:0.1.1-beta
      imagePullPolicy: Always
      name: headlamp-plugins
      volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
    - mountPath: /build/plugins
      name: headlamp-plugins
    volumes:
    - name: headlamp-plugins
      persistentVolumeClaim:
        claimName: headlamp
