apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: cozystack-resource-definition-crd
  namespace: cozy-system
spec:
  chart:
    spec:
      chart: cozystack-resource-definition-crd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cozystack-api
    namespace: cozy-system
  - name: cozystack-controller
    namespace: cozy-system
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: cozystack-resource-definition-crd
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
