apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
  name: kubeovn
  namespace: cozy-kubeovn
spec:
  chart:
    spec:
      chart: cozy-kubeovn
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: kubeovn
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    cozystack:
      nodesHash: fb92163930f26d3ea41890528085344683708b293ca5ce3cc479b2b3bc4e58c1
    kube-ovn:
      ipv4:
        JOIN_CIDR: 100.64.0.0/16
        POD_CIDR: 10.244.0.0/16
        POD_GATEWAY: 10.244.0.1
        SVC_CIDR: 10.96.0.0/16
