apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: cert-manager
  namespace: cozy-cert-manager
spec:
  chart:
    spec:
      chart: cozy-cert-manager
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: cert-manager-crds
    namespace: cozy-cert-manager
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: cert-manager
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
