apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: cilium
  namespace: cozy-cilium
spec:
  chart:
    spec:
      chart: cozy-cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      valuesFiles:
      - values.yaml
      - values-talos.yaml
      - values-kubeovn.yaml
      version: '>= 0.0.0-0'
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: cilium
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
