apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: keycloak-configure
  namespace: cozy-keycloak
spec:
  chart:
    spec:
      chart: cozy-keycloak-configure
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: keycloak-operator
    namespace: cozy-keycloak
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: keycloak-configure
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    cozystack:
      configHash: [redacted
