apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: virtual-machine-control0
  namespace: tenant-legacy
spec:
  chart:
    spec:
      chart: virtual-machine
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.4.0
  interval: 1m0s
  timeout: 5m0s
  values:
    cloudInit: |
      #cloud-config
    external: true
    externalPorts:
    - 22
    - 80
    - 8080
    - 8000
    - 6443
    - 8443
    - 443
    - 5353
    - 2222
    image: ubuntu
    resources:
      cpu: 8
      disk: 50Gi
      memory: 8096M
    running: true
    sshKeys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOOAEa0lEIJwx2xRQtPbEqw4h55yNBEjlxMfW5cqrq5A
      yebyen@kingdon-mbp.turkey.local
    storageClass: replicated
