apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: keycloak
  namespace: cozy-keycloak
spec:
  chart:
    spec:
      chart: cozy-keycloak
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: postgres-operator
    namespace: cozy-postgres-operator
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: keycloak
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
