apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: reloader
  namespace: cozy-reloader
spec:
  chart:
    spec:
      chart: cozy-reloader
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: reloader
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
