apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
  name: capi-providers
  namespace: cozy-cluster-api
spec:
  chart:
    spec:
      chart: cozy-capi-providers
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: capi-operator
    namespace: cozy-cluster-api
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: capi-providers
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
