apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: fluxcd-operator
  namespace: cozy-fluxcd
spec:
  chart:
    spec:
      chart: cozy-fluxcd-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: fluxcd-operator
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
