apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: goldpinger
  namespace: cozy-goldpinger
spec:
  chart:
    spec:
      chart: cozy-goldpinger
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: monitoring-agents
    namespace: cozy-monitoring
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: goldpinger
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
