apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
  name: kubevirt
  namespace: cozy-kubevirt
spec:
  chart:
    spec:
      chart: cozy-kubevirt
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: kubevirt-operator
    namespace: cozy-kubevirt
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 1m
  releaseName: kubevirt
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
