apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
  name: fluxcd
  namespace: cozy-fluxcd
spec:
  chart:
    spec:
      chart: cozy-fluxcd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: fluxcd-operator
    namespace: cozy-fluxcd
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: fluxcd
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
