apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: kubeovn
  namespace: cozy-kubeovn
spec:
  chart:
    spec:
      chart: cozy-kubeovn
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: kubeovn
  suspend: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    cozystack:
      nodesHash: 16c936430da87a4e2a4d1670936fbad7a7e0acd979662e88752861553db280ec
    kube-ovn:
      ipv4:
        JOIN_CIDR: 100.64.0.0/16
        POD_CIDR: 10.244.0.0/16
        POD_GATEWAY: 10.244.0.1
        SVC_CIDR: 10.96.0.0/16
