apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: vertical-pod-autoscaler
  namespace: cozy-vertical-pod-autoscaler
spec:
  chart:
    spec:
      chart: cozy-vertical-pod-autoscaler
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: monitoring-agents
    namespace: cozy-monitoring
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: vertical-pod-autoscaler
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
