apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: monitoring-agents
  namespace: cozy-monitoring
spec:
  chart:
    spec:
      chart: cozy-monitoring-agents
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: victoria-metrics-operator
    namespace: cozy-victoria-metrics-operator
  - name: vertical-pod-autoscaler-crds
    namespace: cozy-vertical-pod-autoscaler
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: monitoring-agents
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    scrapeRules:
      etcd:
        enabled: true
