apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
  name: cilium
  namespace: cozy-cilium
spec:
  chart:
    spec:
      chart: cozy-cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 1m
  releaseName: cilium
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
