apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    reconcile.fluxcd.io/forceAt: "2025-06-07T21:56:54.604438-04:00"
    reconcile.fluxcd.io/requestedAt: "2025-06-07T21:56:54.604438-04:00"
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: victoria-metrics-operator
  namespace: cozy-victoria-metrics-operator
spec:
  chart:
    spec:
      chart: cozy-victoria-metrics-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  - name: cert-manager
    namespace: cozy-cert-manager
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: victoria-metrics-operator
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
