apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/repository: system
  name: kubevirt-cdi-operator
  namespace: cozy-kubevirt-cdi
spec:
  chart:
    spec:
      chart: cozy-kubevirt-cdi-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 1m
  releaseName: kubevirt-cdi-operator
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
