apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/cozy-config-digest: 25819b88d8f4c284beeeb5ec3869b208e99181ff4b6bb0f5e2adf1911879f231
    reconcile.fluxcd.io/forceAt: "2025-09-28T17:01:06.686546456Z"
    reconcile.fluxcd.io/requestedAt: "2025-09-28T17:01:06.686546456Z"
  labels:
    cozystack.io/repository: system
    cozystack.io/system-app: "true"
  name: kubeovn-plunger
  namespace: cozy-kubeovn
spec:
  chart:
    spec:
      chart: cozy-kubeovn-plunger
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '>= 0.0.0-0'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: kubeovn-plunger
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
