machine:
  registries:
    mirrors:
      docker.io:
        endpoints:
          - http://netmoom-13net.turkey.local:5050

      gcr.io:
        endpoints:
          - http://netmoom-13net.turkey.local:5053

      ghcr.io:
        endpoints:
          - http://netmoom-13net.turkey.local:5054

      registry.k8s.io:
        endpoints:
          - http://netmoom-13net.turkey.local:5051
