---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  # Next Revocation: Mar 10, 2025 at 12:59 PM EDT
  - TS_AUTHKEY=tskey-auth-kYBZ........[REDACTED]........3RCV
  - TS_ROUTES=10.96.0.0/16,10.244.0.0/16
  - TS_USERSPACE=true
