---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
  # Next Revocation: Jan 7, 2025 at 10:21 AM EST
  - TS_AUTHKEY=tskey-auth-kVEg........[REDACTED]........W8VJ
  - TS_ROUTES=10.96.0.0/16,10.244.0.0/16,10.17.13.0/24,10.17.12.0/24
