apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: kubernetes-mop
    meta.helm.sh/release-namespace: tenant-test-tenant
  labels:
    app.kubernetes.io/managed-by: Helm
    coztstack.io/target-cluster-name: kubernetes-mop
    cozystack.io/repository: system
    helm.toolkit.fluxcd.io/name: kubernetes-mop
    helm.toolkit.fluxcd.io/namespace: tenant-test-tenant
  name: kubernetes-mop-csi
  namespace: tenant-test-tenant
spec:
  chart:
    spec:
      chart: cozy-kubevirt-csi-node
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: kubernetes-mop
    namespace: tenant-test-tenant
  install:
    createNamespace: true
  interval: 1m
  kubeConfig:
    secretRef:
      name: kubernetes-mop-kubeconfig
  releaseName: csi
  storageNamespace: cozy-csi
  targetNamespace: cozy-csi
