apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: kubernetes-mog
  namespace: tenant-test-tenant
spec:
  chart:
    spec:
      chart: kubernetes
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.5.0
  interval: 1m0s
  timeout: 5m0s
  values:
    addons:
      certManager:
        enabled: false
      fluxcd:
        enabled: false
      ingressNginx:
        enabled: false
    controlPlane:
      replicas: 2
    host: mog.test.moomboo.space
    nodeGroups:
      md0:
        maxReplicas: 10
        minReplicas: 0
        resources:
          cpu: 2
          memory: 1024Mi
        roles:
        - ingress-nginx
