apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:0704fff932252922f8203659165ed3e71ec7c1ae4c611b51807e1310c3e6d72d
    reconcile.fluxcd.io/forceAt: "2025-08-22T20:19:57.639864007Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-22T20:19:57.639864007Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.10.0
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
