apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:a22b2a6d39d409290389d37ac5a3b65b6ceac16b504d3340679e390d14545fc2
    reconcile.fluxcd.io/forceAt: "2025-11-28T20:44:52.732969821Z"
    reconcile.fluxcd.io/requestedAt: "2025-11-28T20:44:52.732969821Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-live
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '*'
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
