apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/cozy-config-digest: 25819b88d8f4c284beeeb5ec3869b208e99181ff4b6bb0f5e2adf1911879f231
    reconcile.fluxcd.io/forceAt: "2025-09-28T17:01:06.686546456Z"
    reconcile.fluxcd.io/requestedAt: "2025-09-28T17:01:06.686546456Z"
  labels:
    cozystack.io/ui: "true"
  name: tenant-root
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '>= 0.0.0-0'
  dependsOn:
  - name: cilium
    namespace: cozy-cilium
  - name: kubeovn
    namespace: cozy-kubeovn
  install:
    remediation:
      retries: -1
  interval: 0s
  releaseName: tenant-root
  upgrade:
    remediation:
      retries: -1
  values:
    etcd: true
    host: moomboo.space
    ingress: true
    isolated: false
    monitoring: true
    seaweedfs: false
