apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:0704fff932252922f8203659165ed3e71ec7c1ae4c611b51807e1310c3e6d72d
    meta.helm.sh/release-name: tenant-root
    meta.helm.sh/release-namespace: tenant-root
    reconcile.fluxcd.io/forceAt: "2025-08-22T20:19:57.599352013Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-22T20:19:57.599352013Z"
  labels:
    app.kubernetes.io/instance: tenant-root
    app.kubernetes.io/managed-by: Helm
    cozystack.io/ui: "true"
    helm.toolkit.fluxcd.io/name: tenant-root
    helm.toolkit.fluxcd.io/namespace: tenant-root
  name: etcd
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: etcd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  values:
    replicas: 1
