apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/managed-by: Helm
    coztstack.io/target-cluster-name: kubernetes-harvey
    cozystack.io/repository: system
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-root
  name: kubernetes-harvey-fluxcd
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: cozy-fluxcd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-root
  - name: kubernetes-harvey-cilium
    namespace: tenant-root
  - name: kubernetes-harvey-fluxcd-operator
    namespace: tenant-root
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      name: kubernetes-harvey-kubeconfig
  releaseName: fluxcd
  storageNamespace: cozy-fluxcd
  targetNamespace: cozy-fluxcd
  upgrade:
    remediation:
      retries: -1
