apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/managed-by: Helm
    coztstack.io/target-cluster-name: kubernetes-harvey
    cozystack.io/repository: system
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-root
  name: kubernetes-harvey-cilium
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: cozy-cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-root
  install:
    createNamespace: true
  interval: 1m
  kubeConfig:
    secretRef:
      name: kubernetes-harvey-kubeconfig
  releaseName: cilium
  storageNamespace: cozy-cilium
  targetNamespace: cozy-cilium
  values:
    cilium:
      autoDirectNodeRoutes: false
      bpf:
        masquerade: true
      cgroup:
        autoMount:
          enabled: true
        hostRoot: /run/cilium/cgroupv2
      cni:
        chainingMode: null
        configMap: ""
        customConf: false
      enableIPv4Masquerade: true
      ipv4NativeRoutingCIDR: ""
      k8sServiceHost: kubernetes-harvey.tenant-root.svc
      k8sServicePort: 6443
      routingMode: tunnel
      tunnel: disabled
