apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:d8d3021d9beab94ade6f5af21e763f1f2911dcf1be0de74103a01eff5df8d625
    reconcile.fluxcd.io/forceAt: "2025-07-23T23:02:25.770425382Z"
    reconcile.fluxcd.io/requestedAt: "2025-07-23T23:02:25.770425382Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.9.1
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
