apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:e1a063ee6c05a8158326527e972b5fa600f66871f111c509cd5bfa0652f69870
    reconcile.fluxcd.io/forceAt: "2025-08-06T18:05:44.284654796Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-06T18:05:44.284654796Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.9.1
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
