apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:5b305aa086df1e58020c7fda2a6da8966da6e8a863a65a88c1f993bf68eea172
    reconcile.fluxcd.io/forceAt: "2025-09-28T17:03:04.806348131Z"
    reconcile.fluxcd.io/requestedAt: "2025-09-28T17:03:04.806348131Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-test
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.10.0
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
