apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: kubernetes-harvey
    meta.helm.sh/release-namespace: tenant-root
  labels:
    app.kubernetes.io/managed-by: Helm
    coztstack.io/target-cluster-name: kubernetes-harvey
    cozystack.io/repository: system
    helm.toolkit.fluxcd.io/name: kubernetes-harvey
    helm.toolkit.fluxcd.io/namespace: tenant-root
  name: kubernetes-harvey-ingress-nginx
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: cozy-ingress-nginx
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-system
        namespace: cozy-system
      version: '*'
  dependsOn:
  - name: kubernetes-harvey
    namespace: tenant-root
  - name: kubernetes-harvey-cilium
    namespace: tenant-root
  install:
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  kubeConfig:
    secretRef:
      name: kubernetes-harvey-kubeconfig
  releaseName: ingress-nginx
  storageNamespace: cozy-ingress-nginx
  targetNamespace: cozy-ingress-nginx
  upgrade:
    remediation:
      retries: -1
  values:
    ingress-nginx:
      controller:
        config:
          proxy-connect-timeout: "10"
          proxy-read-timeout: "10"
        hostNetwork: true
        kind: DaemonSet
        service:
          enabled: false
      fullnameOverride: ingress-nginx
      nodeSelector:
        node-role.kubernetes.io/ingress-nginx: ""
