apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:d8cbfb5758df25a7b9a7c515fe5c79d11d98efd7971966f327d4d27275de11bb
    reconcile.fluxcd.io/forceAt: "2025-12-06T14:09:49.58641472Z"
    reconcile.fluxcd.io/requestedAt: "2025-12-06T14:09:49.58641472Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-live
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '>= 0.0.0-0'
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
