apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: tenant-root
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 1.11.2
  interval: 0s
  values:
    etcd: true
    host: moomboo.space
    ingress: true
    isolated: false
    monitoring: true
