apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:47476134c0fd67c394b338f65d530f0b2bfd4167c313e31079375c9f233f65ea
    reconcile.fluxcd.io/forceAt: "2025-08-07T13:49:13.507059752Z"
    reconcile.fluxcd.io/requestedAt: "2025-08-07T13:49:13.507059752Z"
  labels:
    cozystack.io/ui: "true"
  name: redis-live
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: 0.9.1
  interval: 0s
  values:
    authEnabled: true
    external: true
    replicas: 2
    resourcesPreset: nano
    size: 1Gi
    storageClass: ""
