apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    cozystack.io/tenant-config-digest: sha256:ce85b36096324558cf86352ff4c289203f1199d3a1a892e781da536887540b5e
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: tenant-root
    meta.helm.sh/release-namespace: tenant-root
    reconcile.fluxcd.io/forceAt: "2025-07-12T14:59:01.804409009Z"
    reconcile.fluxcd.io/requestedAt: "2025-07-12T14:59:01.804409009Z"
  labels:
    app.kubernetes.io/instance: tenant-root
    app.kubernetes.io/managed-by: Helm
    cozystack.io/ui: "true"
    helm.toolkit.fluxcd.io/name: tenant-root
    helm.toolkit.fluxcd.io/namespace: tenant-root
  name: monitoring
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: monitoring
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  values:
    metricsStorages:
    - deduplicationInterval: 15s
      name: shortterm
      retentionPeriod: 3d
      storage: 10Gi
    - deduplicationInterval: 5m
      name: longterm
      retentionPeriod: 14d
      storage: 10Gi
    oncall:
      enabled: false
