apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    cozystack.io/ui: "true"
  name: etcd
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: etcd
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-extra
        namespace: cozy-public
      version: '*'
  interval: 0s
  values:
    replicas: 1
